HTMLElement.prototype.wrap=function(r){this.parentNode.insertBefore(r,this),this.parentNode.removeChild(this),r.appendChild(this)},Fluid.events={registerNavbarEvent:function(){var r=jQuery("#navbar");if(r.length!==0){var e=jQuery("#navbar .dropdown-menu");r.offset().top>0&&(r.removeClass("navbar-dark"),e.removeClass("navbar-dark")),Fluid.utils.listenScroll(function(){r[r.offset().top>50?"addClass":"removeClass"]("top-nav-collapse"),e[r.offset().top>50?"addClass":"removeClass"]("dropdown-collapse"),r.offset().top>0?(r.removeClass("navbar-dark"),e.removeClass("navbar-dark")):(r.addClass("navbar-dark"),e.removeClass("navbar-dark"))}),jQuery("#navbar-toggler-btn").on("click",function(){jQuery(".animated-icon").toggleClass("open"),jQuery("#navbar").toggleClass("navbar-col-show")})}},registerParallaxEvent:function(){var r=jQuery('#banner[parallax="true"]');if(r.length!==0){var e=jQuery("#board");if(e.length!==0){var n=function(){var o=jQuery(window).scrollTop()/5,t=parseInt(e.css("margin-top"),10),s=96+t;o>s&&(o=s),r.css({transform:"translate3d(0,"+o+"px,0)"});var a=jQuery(".side-col");a&&a.css({"padding-top":o+"px"})};Fluid.utils.listenScroll(n)}}},registerScrollDownArrowEvent:function(){var r=jQuery(".scroll-down-bar");r.length!==0&&r.on("click",function(){Fluid.utils.scrollToElement("#board",-jQuery("#navbar").height())})},registerScrollTopArrowEvent:function(){var r=jQuery("#scroll-top-button");if(r.length!==0){var e=jQuery("#board");if(e.length!==0){var n=!1,o=!1,t=function(){var a=e[0].getClientRects()[0].right,l=document.body.offsetWidth,i=l-a;n=i>=50,r.css({bottom:n&&o?"20px":"-60px",right:i-64+"px"})};t(),jQuery(window).resize(t);var s=e.offset().top;Fluid.utils.listenScroll(function(){var a=document.body.scrollTop+document.documentElement.scrollTop;o=a>=s,r.css({bottom:n&&o?"20px":"-60px"})}),r.on("click",function(){jQuery("body,html").animate({scrollTop:0,easing:"swing"})})}}},registerImageLoadedEvent:function(){if("NProgress"in window){var r=document.getElementById("banner");if(r){var e=r.style.backgroundImage,n=e.match(/\((.*?)\)/)[1].replace(/(['"])/g,""),o=new Image;o.onload=function(){window.NProgress&&window.NProgress.status!==null&&window.NProgress.inc(.2)},o.src=n,o.complete&&o.onload()}var t=jQuery("main img:not([lazyload])"),s=t.length;for(const a of t){const l=a.onload;a.onload=function(){l&&l(),window.NProgress&&window.NProgress.status!==null&&window.NProgress.inc(.5/s)},a.complete&&a.onload()}}},registerRefreshCallback:function(r){Array.isArray(Fluid.events._refreshCallbacks)||(Fluid.events._refreshCallbacks=[]),Fluid.events._refreshCallbacks.push(r)},refresh:function(){if(Array.isArray(Fluid.events._refreshCallbacks))for(var r of Fluid.events._refreshCallbacks)r instanceof Function&&r()},billboard:function(){"console"in window&&console.log(`
-------------------------------------------------
|                                               |
|      ________  __            _        __      |
|     |_   __  |[  |          (_)      |  ]     |
|       | |_ \\_| | | __   _   __   .--.| |      |
|       |  _|    | |[  | | | [  |/ /'\`\\' |      |
|      _| |_     | | | \\_/ |, | || \\__/  |      |
|     |_____|   [___]'.__.'_/[___]'.__.;__]     |
|                                               |
|            Powered by Hexo x Fluid            |
| https://github.com/fluid-dev/hexo-theme-fluid |
|                                               |
-------------------------------------------------
    `)}};
